import { ClassListItemProps } from "../types/ClassListItem";

export const sampleData: ClassListItemProps[] = [
    {
        subject: "Programming",
        startTime: new Date("2023-07-04 16:30"),
        finishTime: new Date("2023-07-04 19:00"),
        title: "What is OOP?",
        slide: "https://slides.com/oop-intro",
        resource: "https://gitbook.com/oop-intro",
    },
    {
        subject: "Mathematics",
        startTime: new Date("2020-09-02 10:30"),
        finishTime: new Date("2020-09-02 12:00"),
        title: "Introduction to Algebra",
        slide: "https://slides.com/algebra-intro",
        resource: "https://gitbook.com/algebra-intro",
    },
    {
        subject: "Mathematics",
        startTime: new Date("2020-09-02 13:30"),
        finishTime: new Date("2020-09-02 15:00"),
        title: "Geometry Fundamentals",
        slide: "https://slides.com/geometry-fundamentals",
        resource: "https://gitbook.com/geometry-fundamentals",
    },
    {
        subject: "Programming",
        startTime: new Date("2023-07-04 16:30"),
        finishTime: new Date("2023-07-04 19:00"),
        title: "Test?",
        slide: "https://slides.com/oop-intro",
        resource: "https://gitbook.com/oop-intro",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 10:30"),
        finishTime: new Date("2020-09-03 12:00"),
        title: "Ancient Civilizations",
        slide: "https://slides.com/ancient-civilizations",
        resource: "https://gitbook.com/ancient-civilizations",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 13:30"),
        finishTime: new Date("2020-09-03 15:00"),
        title: "World Wars and Their Impact",
        slide: "https://slides.com/world-wars",
        resource: "https://gitbook.com/world-wars",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 10:30"),
        finishTime: new Date("2020-09-03 12:00"),
        title: "Ancient Civilizations",
        slide: "https://slides.com/ancient-civilizations",
        resource: "https://gitbook.com/ancient-civilizations",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 13:30"),
        finishTime: new Date("2020-09-03 15:00"),
        title: "World Wars and Their Impact",
        slide: "https://slides.com/world-wars",
        resource: "https://gitbook.com/world-wars",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 10:30"),
        finishTime: new Date("2020-09-03 12:00"),
        title: "Ancient Civilizations",
        slide: "https://slides.com/ancient-civilizations",
        resource: "https://gitbook.com/ancient-civilizations",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 13:30"),
        finishTime: new Date("2020-09-03 15:00"),
        title: "World Wars and Their Impact",
        slide: "https://slides.com/world-wars",
        resource: "https://gitbook.com/world-wars",
    },

    {
        subject: "History",
        startTime: new Date("2020-09-03 10:30"),
        finishTime: new Date("2020-09-03 12:00"),
        title: "Ancient Civilizations",
        slide: "https://slides.com/ancient-civilizations",
        resource: "https://gitbook.com/ancient-civilizations",
    },
    {
        subject: "History",
        startTime: new Date("2020-09-03 13:30"),
        finishTime: new Date("2020-09-03 15:00"),
        title: "World Wars and Their Impact",
        slide: "https://slides.com/world-wars",
        resource: "https://gitbook.com/world-wars",
    },
];
